In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

sns.set()

In [2]:
raw_data = pd.read_csv('hotel_booking.csv')
raw_data.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [3]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

In [4]:
raw_data.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
dtype: int64

In [5]:
raw_data.describe(include ='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
hotel,119390,2,City Hotel,79330,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_canceled,119390,NaN,NaN,NaN,0.370416,0.482918,0,0,0,1,1
lead_time,119390,NaN,NaN,NaN,104.011,106.863,0,18,69,160,737
arrival_date_year,119390,NaN,NaN,NaN,2016.16,0.707476,2015,2016,2016,2017,2017
arrival_date_month,119390,12,August,13877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_date_week_number,119390,NaN,NaN,NaN,27.1652,13.6051,1,16,28,38,53
arrival_date_day_of_month,119390,NaN,NaN,NaN,15.7982,8.78083,1,8,16,23,31
stays_in_weekend_nights,119390,NaN,NaN,NaN,0.927599,0.998613,0,0,1,2,19
stays_in_week_nights,119390,NaN,NaN,NaN,2.5003,1.90829,0,1,2,3,50
adults,119390,NaN,NaN,NaN,1.8564,0.579261,0,2,2,2,55
children,119386,NaN,NaN,NaN,0.10389,0.398561,0,0,0,0,10
babies,119390,NaN,NaN,NaN,0.00794874,0.0974362,0,0,0,0,10
meal,119390,5,BB,92310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,118902,177,PRT,48590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
market_segment,119390,8,Online TA,56477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distribution_channel,119390,5,TA/TO,97870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,119390,NaN,NaN,NaN,0.0319122,0.175767,0,0,0,0,1
previous_cancellations,119390,NaN,NaN,NaN,0.0871178,0.844336,0,0,0,0,26
previous_bookings_not_canceled,119390,NaN,NaN,NaN,0.137097,1.49744,0,0,0,0,72
reserved_room_type,119390,10,A,85994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
assigned_room_type,119390,12,A,74053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
booking_changes,119390,NaN,NaN,NaN,0.221124,0.652306,0,0,0,0,21
deposit_type,119390,3,No Deposit,104641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agent,103050,NaN,NaN,NaN,86.6934,110.775,1,9,14,229,535
company,6797,NaN,NaN,NaN,189.267,131.655,6,62,179,270,543
days_in_waiting_list,119390,NaN,NaN,NaN,2.32115,17.5947,0,0,0,0,391
customer_type,119390,4,Transient,89613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,119390,NaN,NaN,NaN,101.831,50.5358,-6.38,69.29,94.575,126,5400
required_car_parking_spaces,119390,NaN,NaN,NaN,0.0625178,0.245291,0,0,0,0,8
total_of_special_requests,119390,NaN,NaN,NaN,0.571363,0.792798,0,0,0,1,5
reservation_status,119390,3,Check-Out,75166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reservation_status_date,119390,926,2015-10-21,1461,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,119390,81503,Michael Johnson,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
email,119390,115889,Michael.C@gmail.com,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
phone-number,119390,119390,836-044-1124,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
credit_card,119390,9000,************3627,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
raw_data.duplicated().sum()

0

In [7]:
raw_data.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [101]:
raw_data.company.value_counts()

40.0     927
223.0    784
67.0     267
45.0     250
153.0    215
        ...
229.0      1
213.0      1
416.0      1
320.0      1
461.0      1
Name: company, Length: 352, dtype: int64

In [9]:
raw_data.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card'],
      dtype='object')

In [10]:
droped_col = ['agent','company', 'name', 'email','phone-number', 'credit_card']
data_after_drop = raw_data.drop(columns = droped_col)  

data_after_drop.isna().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
dtype: int64

In [11]:
data_after_drop[data_after_drop['country'].isna() ==True ].is_canceled.value_counts()

0    421
1     67
Name: is_canceled, dtype: int64

In [12]:

data_after_drop['children'] = data_after_drop['children'].map({0:0,1:1,2:2,3:3,10:3})
data_after_drop['babies'] = data_after_drop['babies'].map({0:0,1:1,2:2,9:2,10:2})
data_after_drop['children'] = data_after_drop['children'].fillna(value = 0)
data_no_mv = data_after_drop.dropna().reset_index()

In [13]:

data_no_mv.isna().sum()

index                             0
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [14]:
data_no_mv.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
index,118902,NaN,NaN,NaN,59872.1,34418.3,0,30186.2,59928.5,89662.8,119389
hotel,118902,2,City Hotel,79306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_canceled,118902,NaN,NaN,NaN,0.371373,0.483174,0,0,0,1,1
lead_time,118902,NaN,NaN,NaN,104.308,106.903,0,18,69,161,737
arrival_date_year,118902,NaN,NaN,NaN,2016.16,0.707479,2015,2016,2016,2017,2017
arrival_date_month,118902,12,August,13856,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_date_week_number,118902,NaN,NaN,NaN,27.1667,13.5898,1,16,28,38,53
arrival_date_day_of_month,118902,NaN,NaN,NaN,15.8006,8.78037,1,8,16,23,31
stays_in_weekend_nights,118902,NaN,NaN,NaN,0.928891,0.996211,0,0,1,2,16
stays_in_week_nights,118902,NaN,NaN,NaN,2.50214,1.90016,0,1,2,3,41
adults,118902,NaN,NaN,NaN,1.8584,0.578576,0,2,2,2,55
children,118902,NaN,NaN,NaN,0.104145,0.398222,0,0,0,0,3
babies,118902,NaN,NaN,NaN,0.00782157,0.089608,0,0,0,0,2
meal,118902,5,BB,91867,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,118902,177,PRT,48590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
market_segment,118902,8,Online TA,56403,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distribution_channel,118902,5,TA/TO,97730,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,118902,NaN,NaN,NaN,0.0320096,0.176026,0,0,0,0,1
previous_cancellations,118902,NaN,NaN,NaN,0.087139,0.845855,0,0,0,0,26
previous_bookings_not_canceled,118902,NaN,NaN,NaN,0.131629,1.48465,0,0,0,0,72
reserved_room_type,118902,10,A,85601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
assigned_room_type,118902,12,A,73863,NaN,NaN,NaN,NaN,NaN,NaN,NaN
booking_changes,118902,NaN,NaN,NaN,0.221174,0.652775,0,0,0,0,21
deposit_type,118902,3,No Deposit,104167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
days_in_waiting_list,118902,NaN,NaN,NaN,2.33068,17.6302,0,0,0,0,391
customer_type,118902,4,Transient,89174,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,118902,NaN,NaN,NaN,102.001,50.487,-6.38,70,95,126,5400
required_car_parking_spaces,118902,NaN,NaN,NaN,0.0618829,0.244168,0,0,0,0,8
total_of_special_requests,118902,NaN,NaN,NaN,0.571706,0.792678,0,0,0,1,5
reservation_status,118902,3,Check-Out,74745,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reservation_status_date,118902,926,2015-10-21,1461,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
print('hotel values:\n',data_no_mv.hotel.value_counts())
print('\narrival_date_month values:\n',data_no_mv.arrival_date_month.value_counts())
print('\nmeal values:\n',data_no_mv.meal.value_counts())
print('\nmarket_segment values:\n',data_no_mv.market_segment.value_counts())
print('\ndistribution_channel values:\n',data_no_mv.distribution_channel.value_counts())
print('\nreserved_room_type values:\n',data_no_mv.reserved_room_type.value_counts())
print('\nassigned_room_type values:\n',data_no_mv.assigned_room_type.value_counts())
print('\ndeposit_type values:\n',data_no_mv.deposit_type.value_counts())
print('\ncustomer_type values:\n',data_no_mv.customer_type.value_counts())
print('\nreservation_status values:\n',data_no_mv.reservation_status.value_counts())

hotel values:
 City Hotel      79306
Resort Hotel    39596
Name: hotel, dtype: int64

arrival_date_month values:
 August       13856
July         12628
May          11779
October      11095
April        11045
June         10927
September    10467
March         9739
February      8012
November      6752
December      6728
January       5874
Name: arrival_date_month, dtype: int64

meal values:
 BB           91867
HB           14434
SC           10638
Undefined     1165
FB             798
Name: meal, dtype: int64

market_segment values:
 Online TA        56403
Offline TA/TO    24160
Groups           19806
Direct           12449
Corporate         5111
Complementary      734
Aviation           237
Undefined            2
Name: market_segment, dtype: int64

distribution_channel values:
 TA/TO        97730
Direct       14483
Corporate     6491
GDS            193
Undefined        5
Name: distribution_channel, dtype: int64

reserved_room_type values:
 A    85601
D    19173
E     6497
F     2890
G     2083
B     1118
C      931
H      601
L        6
P        2
Name: reserved_room_type, dtype: int64

assigned_room_type values:
 A    73863
D    25166
E     7738
F     3732
G     2539
C     2354
B     2163
H      708
I      357
K      279
P        2
L        1
Name: assigned_room_type, dtype: int64

deposit_type values:
 No Deposit    104167
Non Refund     14573
Refundable       162
Name: deposit_type, dtype: int64

customer_type values:
 Transient          89174
Transient-Party    25082
Contract            4076
Group                570
Name: customer_type, dtype: int64

reservation_status values:
 Check-Out    74745
Canceled     42954
No-Show       1203
Name: reservation_status, dtype: int64

In [16]:
country = list(set(data_no_mv.country.values))
country

['BFA',
 'IDN',
 'KEN',
 'MUS',
 'HUN',
 'KAZ',
 'BEN',
 'BEL',
 'PRI',
 'TWN',
 'SLV',
 'SLE',
 'KOR',
 'SVN',
 'MAR',
 'UKR',
 'GGY',
 'NGA',
 'UMI',
 'MRT',
 'CMR',
 'ZWE',
 'IRQ',
 'ARG',
 'NIC',
 'ITA',
 'DJI',
 'NAM',
 'DNK',
 'SYR',
 'GNB',
 'AGO',
 'SVK',
 'VEN',
 'SWE',
 'TUR',
 'DZA',
 'VGB',
 'MDG',
 'CYP',
 'MMR',
 'KHM',
 'RUS',
 'SMR',
 'ISL',
 'CHN',
 'NPL',
 'CPV',
 'ETH',
 'EST',
 'JOR',
 'NCL',
 'POL',
 'UGA',
 'MYT',
 'ASM',
 'DEU',
 'LTU',
 'ARE',
 'SEN',
 'AUT',
 'MWI',
 'COM',
 'BLR',
 'PHL',
 'ATA',
 'JAM',
 'HKG',
 'PRT',
 'PYF',
 'GUY',
 'CAF',
 'ZMB',
 'CYM',
 'BHS',
 'PLW',
 'CIV',
 'ABW',
 'ALB',
 'ECU',
 'ARM',
 'ZAF',
 'MCO',
 'TJK',
 'PAK',
 'MKD',
 'NLD',
 'JPN',
 'BRB',
 'NZL',
 'AND',
 'MLI',
 'CHL',
 'LBN',
 'THA',
 'GHA',
 'EGY',
 'OMN',
 'BOL',
 'LVA',
 'MLT',
 'VNM',
 'UZB',
 'GEO',
 'TGO',
 'GAB',
 'AUS',
 'TUN',
 'BGD',
 'FJI',
 'SUR',
 'GLP',
 'GRC',
 'IMN',
 'ISR',
 'BHR',
 'MDV',
 'FIN',
 'JEY',
 'QAT',
 'MOZ',
 'MNE',
 'KWT',
 'FRA',
 'LBY',
 'AIA',
 'MEX',
 'LUX',
 'SYC',
 'KNA',
 'COL',
 'LKA',
 'KIR',
 'ROU',
 'BIH',
 'TZA',
 'SAU',
 'DOM',
 'BWA',
 'FRO',
 'DMA',
 'GBR',
 'GIB',
 'CRI',
 'SGP',
 'AZE',
 'STP',
 'BGR',
 'MAC',
 'BRA',
 'SDN',
 'RWA',
 'NOR',
 'CUB',
 'HRV',
 'ATF',
 'GTM',
 'PRY',
 'CHE',
 'SRB',
 'BDI',
 'IRN',
 'PAN',
 'HND',
 'IND',
 'LCA',
 'TMP',
 'LAO',
 'CZE',
 'USA',
 'LIE',
 'MYS',
 'URY',
 'CN',
 'PER',
 'ESP',
 'IRL']

In [17]:
country_code = pd.read_csv('country_table.csv')
country_code

,Country,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average)
0,Afghanistan,AF,AFG,4,33.0000,65.0
1,Albania,AL,ALB,8,41.0000,20.0
2,Algeria,DZ,DZA,12,28.0000,3.0
3,American Samoa,AS,ASM,16,-14.3333,-170.0
4,Andorra,AD,AND,20,42.5000,1.6
...,...,...,...,...,...,...
251,Wallis and Futuna,WF,WLF,876,-13.3000,-176.2
252,Western Sahara,EH,ESH,732,24.5000,-13.0
253,Yemen,YE,YEM,887,15.0000,48.0
254,Zambia,ZM,ZMB,894,-15.0000,30.0
255,Zimbabwe,ZW,ZWE,716,-20.0000,30.0

In [18]:
lon = {d['Alpha-3 code']: d['Longitude (average)'] for d in country_code.to_dict(orient='records')}

lat = {d['Alpha-3 code']: d['Latitude (average)'] for d in country_code.to_dict(orient='records')}

In [19]:
data_no_mv['Latitude'] = data_no_mv['country'].map(lat)

data_no_mv['Longitude'] = data_no_mv['country'].map(lon)

In [20]:
data_no_mv.columns.values

array(['index', 'hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'Latitude',
       'Longitude'], dtype=object)

In [21]:
col =['hotel', 'lead_time', 'arrival_date_year','arrival_date_month', 'arrival_date_week_number','arrival_date_day_of_month', 'stays_in_weekend_nights',
'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
'market_segment', 'distribution_channel',
'is_repeated_guest', 'previous_cancellations',
'previous_bookings_not_canceled', 'reserved_room_type',
'assigned_room_type', 'booking_changes', 'deposit_type',
'days_in_waiting_list', 'customer_type', 'adr',
'required_car_parking_spaces', 'total_of_special_requests',
'reservation_status', 'reservation_status_date', 'Latitude',
'Longitude','is_canceled']
data_with_geo = data_no_mv[col]
data_with_geo.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
hotel,118902,2,City Hotel,79306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lead_time,118902,NaN,NaN,NaN,104.308,106.903,0,18,69,161,737
arrival_date_year,118902,NaN,NaN,NaN,2016.16,0.707479,2015,2016,2016,2017,2017
arrival_date_month,118902,12,August,13856,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_date_week_number,118902,NaN,NaN,NaN,27.1667,13.5898,1,16,28,38,53
arrival_date_day_of_month,118902,NaN,NaN,NaN,15.8006,8.78037,1,8,16,23,31
stays_in_weekend_nights,118902,NaN,NaN,NaN,0.928891,0.996211,0,0,1,2,16
stays_in_week_nights,118902,NaN,NaN,NaN,2.50214,1.90016,0,1,2,3,41
adults,118902,NaN,NaN,NaN,1.8584,0.578576,0,2,2,2,55
children,118902,NaN,NaN,NaN,0.104145,0.398222,0,0,0,0,3
babies,118902,NaN,NaN,NaN,0.00782157,0.089608,0,0,0,0,2
meal,118902,5,BB,91867,NaN,NaN,NaN,NaN,NaN,NaN,NaN
market_segment,118902,8,Online TA,56403,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distribution_channel,118902,5,TA/TO,97730,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,118902,NaN,NaN,NaN,0.0320096,0.176026,0,0,0,0,1
previous_cancellations,118902,NaN,NaN,NaN,0.087139,0.845855,0,0,0,0,26
previous_bookings_not_canceled,118902,NaN,NaN,NaN,0.131629,1.48465,0,0,0,0,72
reserved_room_type,118902,10,A,85601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
assigned_room_type,118902,12,A,73863,NaN,NaN,NaN,NaN,NaN,NaN,NaN
booking_changes,118902,NaN,NaN,NaN,0.221174,0.652775,0,0,0,0,21
deposit_type,118902,3,No Deposit,104167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
days_in_waiting_list,118902,NaN,NaN,NaN,2.33068,17.6302,0,0,0,0,391
customer_type,118902,4,Transient,89174,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,118902,NaN,NaN,NaN,102.001,50.487,-6.38,70,95,126,5400
required_car_parking_spaces,118902,NaN,NaN,NaN,0.0618829,0.244168,0,0,0,0,8
total_of_special_requests,118902,NaN,NaN,NaN,0.571706,0.792678,0,0,0,1,5
reservation_status,118902,3,Check-Out,74745,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reservation_status_date,118902,926,2015-10-21,1461,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,117620,NaN,NaN,NaN,42.2094,12.5685,-90,39.5,40,50.8333,65
Longitude,117620,NaN,NaN,NaN,-1.42068,25.7254,-170,-8,-4,2,175
is_canceled,118902,NaN,NaN,NaN,0.371373,0.483174,0,0,0,1,1

In [22]:
data_with_geo['meal'].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [23]:
data_with_geo['hotel']= data_with_geo['hotel'].map({'Resort Hotel':0,'City Hotel':1})
data_with_geo['arrival_date_month']=data_with_geo['arrival_date_month'].map({'January':1,'February':2,'March':3,'April':4,'May':5,'June':6,'July':7,'August':8,'September':9, 'October':10,'November':11, 'December':12})

data_with_geo

<ipython-input-23-ef02d8caee70>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_with_geo['hotel']= data_with_geo['hotel'].map({'Resort Hotel':0,'City Hotel':1})
<ipython-input-23-ef02d8caee70>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_with_geo['arrival_date_month']=data_with_geo['arrival_date_month'].map({'January':1,'February':2,'March':3,'April':4,'May':5,'June':6,'July':7,'August':8,'September':9, 'October':10,'November':11, 'December':12})

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,Latitude,Longitude,is_canceled
0,0,342,2015,7,27,1,0,0,2,0.0,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,39.5000,-8.0,0
1,0,737,2015,7,27,1,0,0,2,0.0,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,39.5000,-8.0,0
2,0,7,2015,7,27,1,0,1,1,0.0,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,54.0000,-2.0,0
3,0,13,2015,7,27,1,0,1,1,0.0,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,54.0000,-2.0,0
4,0,14,2015,7,27,1,0,2,2,0.0,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,54.0000,-2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,1,23,2017,8,35,30,2,5,2,0.0,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,50.8333,4.0,0
118898,1,102,2017,8,35,31,2,5,3,0.0,...,0,Transient,225.43,0,2,Check-Out,2017-09-07,46.0000,2.0,0
118899,1,34,2017,8,35,31,2,5,2,0.0,...,0,Transient,157.71,0,4,Check-Out,2017-09-07,51.0000,9.0,0
118900,1,109,2017,8,35,31,2,5,2,0.0,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,54.0000,-2.0,0
118901,1,205,2017,8,35,29,2,7,2,0.0,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,51.0000,9.0,0

In [24]:
cols =['hotel', 'lead_time','arrival_date_month','arrival_date_day_of_month', 'stays_in_weekend_nights',
'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
'market_segment', 'distribution_channel',
'is_repeated_guest', 'previous_cancellations',
'previous_bookings_not_canceled', 'reserved_room_type',
'assigned_room_type', 'booking_changes', 'deposit_type',
'days_in_waiting_list', 'customer_type', 'adr',
'required_car_parking_spaces', 'total_of_special_requests',
'reservation_status', 'Latitude',
'Longitude','is_canceled']

data_clean = data_with_geo[cols]
data_clean.shape

(118902, 28)

In [25]:
data_clean.is_canceled.sum()/118902

0.3713730635313115

In [26]:
data_with_dummies = pd.get_dummies(data_clean, drop_first=True)
data_with_dummies.columns.values

array(['hotel', 'lead_time', 'arrival_date_month',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests', 'Latitude', 'Longitude',
       'is_canceled', 'meal_FB', 'meal_HB', 'meal_SC', 'meal_Undefined',
       'market_segment_Complementary', 'market_segment_Corporate',
       'market_segment_Direct', 'market_segment_Groups',
       'market_segment_Offline TA/TO', 'market_segment_Online TA',
       'market_segment_Undefined', 'distribution_channel_Direct',
       'distribution_channel_GDS', 'distribution_channel_TA/TO',
       'distribution_channel_Undefined', 'reserved_room_type_B',
       'reserved_room_type_C', 'reserved_room_type_D',
       'reserved_room_type_E', 'reserved_room_type_F',
       'reserved_room_type_G', 'reserved_room_type_H',
       'reserved_room_type_L', 'reserved_room_type_P',
       'assigned_room_type_B', 'assigned_room_type_C',
       'assigned_room_type_D', 'assigned_room_type_E',
       'assigned_room_type_F', 'assigned_room_type_G',
       'assigned_room_type_H', 'assigned_room_type_I',
       'assigned_room_type_K', 'assigned_room_type_L',
       'assigned_room_type_P', 'deposit_type_Non Refund',
       'deposit_type_Refundable', 'customer_type_Group',
       'customer_type_Transient', 'customer_type_Transient-Party',
       'reservation_status_Check-Out', 'reservation_status_No-Show'],
      dtype=object)

In [52]:
data_with_dummies.shape

(118902, 62)

In [53]:
columns_arr = ['hotel', 'lead_time', 'arrival_date_month',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests',
        'meal_FB', 'meal_HB', 'meal_SC', 'meal_Undefined',
       'market_segment_Complementary', 'market_segment_Corporate',
       'market_segment_Direct', 'market_segment_Groups',
       'market_segment_Offline TA/TO', 'market_segment_Online TA',
       'market_segment_Undefined', 'distribution_channel_Direct',
       'distribution_channel_GDS', 'distribution_channel_TA/TO',
       'distribution_channel_Undefined', 'reserved_room_type_B',
       'reserved_room_type_C', 'reserved_room_type_D',
       'reserved_room_type_E', 'reserved_room_type_F',
       'reserved_room_type_G', 'reserved_room_type_H',
       'reserved_room_type_L', 'reserved_room_type_P',
       'assigned_room_type_B', 'assigned_room_type_C',
       'assigned_room_type_D', 'assigned_room_type_E',
       'assigned_room_type_F', 'assigned_room_type_G',
       'assigned_room_type_H', 'assigned_room_type_I',
       'assigned_room_type_K', 'assigned_room_type_L',
       'assigned_room_type_P', 'deposit_type_Non Refund',
       'deposit_type_Refundable', 'customer_type_Group',
       'customer_type_Transient', 'customer_type_Transient-Party',
       'reservation_status_Check-Out', 'reservation_status_No-Show','is_canceled']
data_rearranged = data_with_dummies[columns_arr]

In [54]:
targets = data_rearranged['is_canceled']
unscaled_inputs = data_rearranged.iloc[:,:-1]

In [55]:
targets.describe(include='all').T

count    118902.000000
mean          0.371373
std           0.483174
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: is_canceled, dtype: float64

In [56]:
unscaled_inputs.describe(include='all').T

,count,mean,std,min,25%,50%,75%,max
hotel,118902.0,0.666986,0.471293,0.00,0.0,1.0,1.0,1.0
lead_time,118902.0,104.308027,106.903127,0.00,18.0,69.0,161.0,737.0
arrival_date_month,118902.0,6.552934,3.087010,1.00,4.0,7.0,9.0,12.0
arrival_date_day_of_month,118902.0,15.800567,8.780371,1.00,8.0,16.0,23.0,31.0
stays_in_weekend_nights,118902.0,0.928891,0.996211,0.00,0.0,1.0,2.0,16.0
stays_in_week_nights,118902.0,2.502136,1.900165,0.00,1.0,2.0,3.0,41.0
adults,118902.0,1.858404,0.578576,0.00,2.0,2.0,2.0,55.0
children,118902.0,0.104145,0.398222,0.00,0.0,0.0,0.0,3.0
babies,118902.0,0.007822,0.089608,0.00,0.0,0.0,0.0,2.0
is_repeated_guest,118902.0,0.032010,0.176026,0.00,0.0,0.0,0.0,1.0
previous_cancellations,118902.0,0.087139,0.845855,0.00,0.0,0.0,0.0,26.0
previous_bookings_not_canceled,118902.0,0.131629,1.484647,0.00,0.0,0.0,0.0,72.0
booking_changes,118902.0,0.221174,0.652775,0.00,0.0,0.0,0.0,21.0
days_in_waiting_list,118902.0,2.330676,17.630161,0.00,0.0,0.0,0.0,391.0
adr,118902.0,102.000808,50.487004,-6.38,70.0,95.0,126.0,5400.0
required_car_parking_spaces,118902.0,0.061883,0.244168,0.00,0.0,0.0,0.0,8.0
total_of_special_requests,118902.0,0.571706,0.792678,0.00,0.0,0.0,1.0,5.0
meal_FB,118902.0,0.006711,0.081648,0.00,0.0,0.0,0.0,1.0
meal_HB,118902.0,0.121394,0.326586,0.00,0.0,0.0,0.0,1.0
meal_SC,118902.0,0.089469,0.285420,0.00,0.0,0.0,0.0,1.0
meal_Undefined,118902.0,0.009798,0.098499,0.00,0.0,0.0,0.0,1.0
market_segment_Complementary,118902.0,0.006173,0.078327,0.00,0.0,0.0,0.0,1.0
market_segment_Corporate,118902.0,0.042985,0.202824,0.00,0.0,0.0,0.0,1.0
market_segment_Direct,118902.0,0.104700,0.306167,0.00,0.0,0.0,0.0,1.0
market_segment_Groups,118902.0,0.166574,0.372597,0.00,0.0,0.0,0.0,1.0
market_segment_Offline TA/TO,118902.0,0.203193,0.402376,0.00,0.0,0.0,0.0,1.0
market_segment_Online TA,118902.0,0.474365,0.499345,0.00,0.0,0.0,1.0,1.0
market_segment_Undefined,118902.0,0.000017,0.004101,0.00,0.0,0.0,0.0,1.0
distribution_channel_Direct,118902.0,0.121806,0.327063,0.00,0.0,0.0,0.0,1.0
distribution_channel_GDS,118902.0,0.001623,0.040256,0.00,0.0,0.0,0.0,1.0
distribution_channel_TA/TO,118902.0,0.821937,0.382567,0.00,1.0,1.0,1.0,1.0
distribution_channel_Undefined,118902.0,0.000042,0.006485,0.00,0.0,0.0,0.0,1.0
reserved_room_type_B,118902.0,0.009403,0.096511,0.00,0.0,0.0,0.0,1.0
reserved_room_type_C,118902.0,0.007830,0.088140,0.00,0.0,0.0,0.0,1.0
reserved_room_type_D,118902.0,0.161250,0.367763,0.00,0.0,0.0,0.0,1.0
reserved_room_type_E,118902.0,0.054642,0.227280,0.00,0.0,0.0,0.0,1.0
reserved_room_type_F,118902.0,0.024306,0.153997,0.00,0.0,0.0,0.0,1.0
reserved_room_type_G,118902.0,0.017519,0.131194,0.00,0.0,0.0,0.0,1.0
reserved_room_type_H,118902.0,0.005055,0.070916,0.00,0.0,0.0,0.0,1.0
reserved_room_type_L,118902.0,0.000050,0.007103,0.00,0.0,0.0,0.0,1.0
reserved_room_type_P,118902.0,0.000017,0.004101,0.00,0.0,0.0,0.0,1.0
assigned_room_type_B,118902.0,0.018191,0.133644,0.00,0.0,0.0,0.0,1.0
assigned_room_type_C,118902.0,0.019798,0.139306,0.00,0.0,0.0,0.0,1.0
assigned_room_type_D,118902.0,0.211653,0.408482,0.00,0.0,0.0,0.0,1.0
assigned_room_type_E,118902.0,0.065079,0.246666,0.00,0.0,0.0,0.0,1.0
assigned_room_type_F,118902.0,0.031387,0.174363,0.00,0.0,0.0,0.0,1.0
assigned_room_type_G,118902.0,0.021354,0.144561,0.00,0.0,0.0,0.0,1.0
assigned_room_type_H,118902.0,0.005954,0.076936,0.00,0.0,0.0,0.0,1.0
assigned_room_type_I,118902.0,0.003002,0.054713,0.00,0.0,0.0,0.0,1.0
assigned_room_type_K,118902.0,0.002346,0.048384,0.00,0.0,0.0,0.0,1.0
assigned_room_type_L,118902.0,0.000008,0.002900,0.00,0.0,0.0,0.0,1.0
assigned_room_type_P,118902.0,0.000017,0.004101,0.00,0.0,0.0,0.0,1.0
deposit_type_Non Refund,118902.0,0.122563,0.327936,0.00,0.0,0.0,0.0,1.0
deposit_type_Refundable,118902.0,0.001362,0.036887,0.00,0.0,0.0,0.0,1.0
customer_type_Group,118902.0,0.004794,0.069072,0.00,0.0,0.0,0.0,1.0
customer_type_Transient,118902.0,0.749979,0.433027,0.00,0.0,1.0,1.0,1.0
customer_type_Transient-Party,118902.0,0.210947,0.407982,0.00,0.0,0.0,0.0,1.0
reservation_status_Check-Out,118902.0,0.628627,0.483174,0.00,0.0,1.0,1.0,1.0
reservation_status_No-Show,118902.0,0.010118,0.100076,0.00,0.0,0.0,0.0,1.0

In [57]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [58]:
scaler.fit(unscaled_inputs)

StandardScaler()

In [59]:
scaled_inputs = scaler.transform(unscaled_inputs)

In [60]:
scaled_inputs

array([[-1.4152311 ,  2.22344265,  0.1448222 , ..., -0.51705098,
         0.76861474, -0.1010989 ],
       [-1.4152311 ,  5.91839219,  0.1448222 , ..., -0.51705098,
         0.76861474, -0.1010989 ],
       [-1.4152311 , -0.91024873,  0.1448222 , ..., -0.51705098,
         0.76861474, -0.1010989 ],
       ...,
       [ 0.70659838, -0.65768256,  0.46876166, ..., -0.51705098,
         0.76861474, -0.1010989 ],
       [ 0.70659838,  0.04389014,  0.46876166, ..., -0.51705098,
         0.76861474, -0.1010989 ],
       [ 0.70659838,  0.94190319,  0.46876166, ..., -0.51705098,
         0.76861474, -0.1010989 ]])

In [61]:
scaled_inputs.shape

(118902, 59)

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
# check how this method works
train_test_split(scaled_inputs, targets)

[array([[ 0.70659838, -0.4331793 , -0.17911725, ..., -0.51705098,
          0.76861474, -0.1010989 ],
        [ 0.70659838, -0.97572885,  0.79270111, ...,  1.93404526,
          0.76861474, -0.1010989 ],
        [-1.4152311 , -0.97572885,  1.76451947, ..., -0.51705098,
          0.76861474, -0.1010989 ],
        ...,
        [-1.4152311 ,  0.48354236, -0.50305671, ...,  1.93404526,
          0.76861474, -0.1010989 ],
        [ 0.70659838,  0.80158865, -0.82699616, ...,  1.93404526,
          0.76861474, -0.1010989 ],
        [ 0.70659838, -0.97572885, -0.50305671, ..., -0.51705098,
          0.76861474, -0.1010989 ]]),
 array([[-1.4152311 , -0.92895734,  1.44058002, ..., -0.51705098,
          0.76861474, -0.1010989 ],
        [-1.4152311 , -0.68574547,  1.44058002, ...,  1.93404526,
          0.76861474, -0.1010989 ],
        [-1.4152311 ,  0.10001595,  0.46876166, ..., -0.51705098,
          0.76861474, -0.1010989 ],
        ...,
        [ 0.70659838, -0.33963627,  0.79270111, ...,  1.93404526,
          0.76861474, -0.1010989 ],
        [ 0.70659838, -0.50801372,  0.46876166, ..., -0.51705098,
         -1.30104193, -0.1010989 ],
        [-1.4152311 ,  1.3160753 ,  0.46876166, ..., -0.51705098,
         -1.30104193, -0.1010989 ]]),
 90362    0
 97821    0
 30674    0
 53507    1
 61634    1
         ..
 9628     1
 36405    0
 35802    0
 80881    0
 88306    0
 Name: is_canceled, Length: 89176, dtype: int64,
 30036    0
 17784    0
 26593    0
 56617    1
 7        0
         ..
 62       0
 57570    1
 43541    0
 73040    1
 13484    1
 Name: is_canceled, Length: 29726, dtype: int64]

In [75]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, test_size = 0.2, random_state = 20)

In [76]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(95121, 59) (95121,)

In [77]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(23781, 59) (23781,)

In [78]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

In [79]:
# create a logistic regression object
reg = LogisticRegression()

In [83]:
# fit our train inputs
# that is basically the whole training part of the machine learning
reg.fit(x_train,y_train)

LogisticRegression()

In [84]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

1.0

In [85]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

1.0

In [86]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [87]:
model_outputs.shape[0]

95121

In [88]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

1.0

In [89]:
reg.intercept_

array([-2.58711257])

In [90]:
reg.coef_

array([[ 2.98264137e-03,  2.08955148e-01,  1.43349679e-02,
         8.13413723e-04,  8.70752232e-03,  3.45907681e-02,
         4.58974135e-02,  3.30206760e-02,  6.31032776e-03,
        -4.64988680e-02,  2.18090571e-01, -5.43064178e-02,
        -1.00101110e-01, -3.78670512e-03,  9.31994142e-02,
        -3.72673792e-01, -2.38750117e-01,  2.11848093e-02,
        -2.18210455e-02, -3.86079731e-03, -2.12138087e-02,
         1.07574914e-02, -1.40622987e-02, -4.53923149e-02,
         5.45830415e-02, -1.18890999e-01,  9.00309317e-02,
         8.11223759e-03, -4.32219731e-02, -1.10878817e-02,
         3.55276036e-02,  8.98194366e-03,  2.86711706e-02,
         3.82154374e-02,  9.37340933e-02,  6.98117938e-02,
         3.69083622e-02,  4.49134358e-02,  1.71306453e-02,
         1.97820898e-03,  5.86404127e-03, -4.15938300e-02,
        -6.71010989e-02, -1.65424028e-01, -9.92778419e-02,
        -8.62644479e-02, -7.21230752e-02, -2.44189729e-02,
        -6.91528614e-02, -4.28367038e-02,  6.62506225e-03,
         5.86404127e-03,  6.02022244e-01, -2.44511231e-03,
        -2.19104261e-02,  1.02557357e-01, -4.76930206e-02,
        -8.65634005e+00,  2.34044054e-01]])

In [91]:
unscaled_inputs.columns.values

array(['hotel', 'lead_time', 'arrival_date_month',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests', 'meal_FB', 'meal_HB', 'meal_SC',
       'meal_Undefined', 'market_segment_Complementary',
       'market_segment_Corporate', 'market_segment_Direct',
       'market_segment_Groups', 'market_segment_Offline TA/TO',
       'market_segment_Online TA', 'market_segment_Undefined',
       'distribution_channel_Direct', 'distribution_channel_GDS',
       'distribution_channel_TA/TO', 'distribution_channel_Undefined',
       'reserved_room_type_B', 'reserved_room_type_C',
       'reserved_room_type_D', 'reserved_room_type_E',
       'reserved_room_type_F', 'reserved_room_type_G',
       'reserved_room_type_H', 'reserved_room_type_L',
       'reserved_room_type_P', 'assigned_room_type_B',
       'assigned_room_type_C', 'assigned_room_type_D',
       'assigned_room_type_E', 'assigned_room_type_F',
       'assigned_room_type_G', 'assigned_room_type_H',
       'assigned_room_type_I', 'assigned_room_type_K',
       'assigned_room_type_L', 'assigned_room_type_P',
       'deposit_type_Non Refund', 'deposit_type_Refundable',
       'customer_type_Group', 'customer_type_Transient',
       'customer_type_Transient-Party', 'reservation_status_Check-Out',
       'reservation_status_No-Show'], dtype=object)

In [92]:
feature_name = unscaled_inputs.columns.values

In [93]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

                      Feature name  Coefficient
0                            hotel     0.002983
1                        lead_time     0.208955
2               arrival_date_month     0.014335
3        arrival_date_day_of_month     0.000813
4          stays_in_weekend_nights     0.008708
5             stays_in_week_nights     0.034591
6                           adults     0.045897
7                         children     0.033021
8                           babies     0.006310
9                is_repeated_guest    -0.046499
10          previous_cancellations     0.218091
11  previous_bookings_not_canceled    -0.054306
12                 booking_changes    -0.100101
13            days_in_waiting_list    -0.003787
14                             adr     0.093199
15     required_car_parking_spaces    -0.372674
16       total_of_special_requests    -0.238750
17                         meal_FB     0.021185
18                         meal_HB    -0.021821
19                         meal_SC    -0.003861
20                  meal_Undefined    -0.021214
21    market_segment_Complementary     0.010757
22        market_segment_Corporate    -0.014062
23           market_segment_Direct    -0.045392
24           market_segment_Groups     0.054583
25    market_segment_Offline TA/TO    -0.118891
26        market_segment_Online TA     0.090031
27        market_segment_Undefined     0.008112
28     distribution_channel_Direct    -0.043222
29        distribution_channel_GDS    -0.011088
30      distribution_channel_TA/TO     0.035528
31  distribution_channel_Undefined     0.008982
32            reserved_room_type_B     0.028671
33            reserved_room_type_C     0.038215
34            reserved_room_type_D     0.093734
35            reserved_room_type_E     0.069812
36            reserved_room_type_F     0.036908
37            reserved_room_type_G     0.044913
38            reserved_room_type_H     0.017131
39            reserved_room_type_L     0.001978
40            reserved_room_type_P     0.005864
41            assigned_room_type_B    -0.041594
42            assigned_room_type_C    -0.067101
43            assigned_room_type_D    -0.165424
44            assigned_room_type_E    -0.099278
45            assigned_room_type_F    -0.086264
46            assigned_room_type_G    -0.072123
47            assigned_room_type_H    -0.024419
48            assigned_room_type_I    -0.069153
49            assigned_room_type_K    -0.042837
50            assigned_room_type_L     0.006625
51            assigned_room_type_P     0.005864
52         deposit_type_Non Refund     0.602022
53         deposit_type_Refundable    -0.002445
54             customer_type_Group    -0.021910
55         customer_type_Transient     0.102557
56   customer_type_Transient-Party    -0.047693
57    reservation_status_Check-Out    -8.656340
58      reservation_status_No-Show     0.234044

In [94]:
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

                      Feature name  Coefficient
0                        Intercept    -2.587113
1                            hotel     0.002983
2                        lead_time     0.208955
3               arrival_date_month     0.014335
4        arrival_date_day_of_month     0.000813
5          stays_in_weekend_nights     0.008708
6             stays_in_week_nights     0.034591
7                           adults     0.045897
8                         children     0.033021
9                           babies     0.006310
10               is_repeated_guest    -0.046499
11          previous_cancellations     0.218091
12  previous_bookings_not_canceled    -0.054306
13                 booking_changes    -0.100101
14            days_in_waiting_list    -0.003787
15                             adr     0.093199
16     required_car_parking_spaces    -0.372674
17       total_of_special_requests    -0.238750
18                         meal_FB     0.021185
19                         meal_HB    -0.021821
20                         meal_SC    -0.003861
21                  meal_Undefined    -0.021214
22    market_segment_Complementary     0.010757
23        market_segment_Corporate    -0.014062
24           market_segment_Direct    -0.045392
25           market_segment_Groups     0.054583
26    market_segment_Offline TA/TO    -0.118891
27        market_segment_Online TA     0.090031
28        market_segment_Undefined     0.008112
29     distribution_channel_Direct    -0.043222
30        distribution_channel_GDS    -0.011088
31      distribution_channel_TA/TO     0.035528
32  distribution_channel_Undefined     0.008982
33            reserved_room_type_B     0.028671
34            reserved_room_type_C     0.038215
35            reserved_room_type_D     0.093734
36            reserved_room_type_E     0.069812
37            reserved_room_type_F     0.036908
38            reserved_room_type_G     0.044913
39            reserved_room_type_H     0.017131
40            reserved_room_type_L     0.001978
41            reserved_room_type_P     0.005864
42            assigned_room_type_B    -0.041594
43            assigned_room_type_C    -0.067101
44            assigned_room_type_D    -0.165424
45            assigned_room_type_E    -0.099278
46            assigned_room_type_F    -0.086264
47            assigned_room_type_G    -0.072123
48            assigned_room_type_H    -0.024419
49            assigned_room_type_I    -0.069153
50            assigned_room_type_K    -0.042837
51            assigned_room_type_L     0.006625
52            assigned_room_type_P     0.005864
53         deposit_type_Non Refund     0.602022
54         deposit_type_Refundable    -0.002445
55             customer_type_Group    -0.021910
56         customer_type_Transient     0.102557
57   customer_type_Transient-Party    -0.047693
58    reservation_status_Check-Out    -8.656340
59      reservation_status_No-Show     0.234044

In [95]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [96]:
summary_table

                      Feature name  Coefficient  Odds_ratio
0                        Intercept    -2.587113    0.075237
1                            hotel     0.002983    1.002987
2                        lead_time     0.208955    1.232390
3               arrival_date_month     0.014335    1.014438
4        arrival_date_day_of_month     0.000813    1.000814
5          stays_in_weekend_nights     0.008708    1.008746
6             stays_in_week_nights     0.034591    1.035196
7                           adults     0.045897    1.046967
8                         children     0.033021    1.033572
9                           babies     0.006310    1.006330
10               is_repeated_guest    -0.046499    0.954566
11          previous_cancellations     0.218091    1.243700
12  previous_bookings_not_canceled    -0.054306    0.947142
13                 booking_changes    -0.100101    0.904746
14            days_in_waiting_list    -0.003787    0.996220
15                             adr     0.093199    1.097681
16     required_car_parking_spaces    -0.372674    0.688890
17       total_of_special_requests    -0.238750    0.787612
18                         meal_FB     0.021185    1.021411
19                         meal_HB    -0.021821    0.978415
20                         meal_SC    -0.003861    0.996147
21                  meal_Undefined    -0.021214    0.979010
22    market_segment_Complementary     0.010757    1.010816
23        market_segment_Corporate    -0.014062    0.986036
24           market_segment_Direct    -0.045392    0.955623
25           market_segment_Groups     0.054583    1.056100
26    market_segment_Offline TA/TO    -0.118891    0.887905
27        market_segment_Online TA     0.090031    1.094208
28        market_segment_Undefined     0.008112    1.008145
29     distribution_channel_Direct    -0.043222    0.957699
30        distribution_channel_GDS    -0.011088    0.988973
31      distribution_channel_TA/TO     0.035528    1.036166
32  distribution_channel_Undefined     0.008982    1.009022
33            reserved_room_type_B     0.028671    1.029086
34            reserved_room_type_C     0.038215    1.038955
35            reserved_room_type_D     0.093734    1.098268
36            reserved_room_type_E     0.069812    1.072306
37            reserved_room_type_F     0.036908    1.037598
38            reserved_room_type_G     0.044913    1.045937
39            reserved_room_type_H     0.017131    1.017278
40            reserved_room_type_L     0.001978    1.001980
41            reserved_room_type_P     0.005864    1.005881
42            assigned_room_type_B    -0.041594    0.959259
43            assigned_room_type_C    -0.067101    0.935101
44            assigned_room_type_D    -0.165424    0.847534
45            assigned_room_type_E    -0.099278    0.905491
46            assigned_room_type_F    -0.086264    0.917352
47            assigned_room_type_G    -0.072123    0.930416
48            assigned_room_type_H    -0.024419    0.975877
49            assigned_room_type_I    -0.069153    0.933184
50            assigned_room_type_K    -0.042837    0.958068
51            assigned_room_type_L     0.006625    1.006647
52            assigned_room_type_P     0.005864    1.005881
53         deposit_type_Non Refund     0.602022    1.825807
54         deposit_type_Refundable    -0.002445    0.997558
55             customer_type_Group    -0.021910    0.978328
56         customer_type_Transient     0.102557    1.108001
57   customer_type_Transient-Party    -0.047693    0.953426
58    reservation_status_Check-Out    -8.656340    0.000174
59      reservation_status_No-Show     0.234044    1.263700

In [97]:
summary_table.sort_values('Odds_ratio', ascending=False)

                      Feature name  Coefficient  Odds_ratio
53         deposit_type_Non Refund     0.602022    1.825807
59      reservation_status_No-Show     0.234044    1.263700
11          previous_cancellations     0.218091    1.243700
2                        lead_time     0.208955    1.232390
56         customer_type_Transient     0.102557    1.108001
35            reserved_room_type_D     0.093734    1.098268
15                             adr     0.093199    1.097681
27        market_segment_Online TA     0.090031    1.094208
36            reserved_room_type_E     0.069812    1.072306
25           market_segment_Groups     0.054583    1.056100
7                           adults     0.045897    1.046967
38            reserved_room_type_G     0.044913    1.045937
34            reserved_room_type_C     0.038215    1.038955
37            reserved_room_type_F     0.036908    1.037598
31      distribution_channel_TA/TO     0.035528    1.036166
6             stays_in_week_nights     0.034591    1.035196
8                         children     0.033021    1.033572
33            reserved_room_type_B     0.028671    1.029086
18                         meal_FB     0.021185    1.021411
39            reserved_room_type_H     0.017131    1.017278
3               arrival_date_month     0.014335    1.014438
22    market_segment_Complementary     0.010757    1.010816
32  distribution_channel_Undefined     0.008982    1.009022
5          stays_in_weekend_nights     0.008708    1.008746
28        market_segment_Undefined     0.008112    1.008145
51            assigned_room_type_L     0.006625    1.006647
9                           babies     0.006310    1.006330
41            reserved_room_type_P     0.005864    1.005881
52            assigned_room_type_P     0.005864    1.005881
1                            hotel     0.002983    1.002987
40            reserved_room_type_L     0.001978    1.001980
4        arrival_date_day_of_month     0.000813    1.000814
54         deposit_type_Refundable    -0.002445    0.997558
14            days_in_waiting_list    -0.003787    0.996220
20                         meal_SC    -0.003861    0.996147
30        distribution_channel_GDS    -0.011088    0.988973
23        market_segment_Corporate    -0.014062    0.986036
21                  meal_Undefined    -0.021214    0.979010
19                         meal_HB    -0.021821    0.978415
55             customer_type_Group    -0.021910    0.978328
48            assigned_room_type_H    -0.024419    0.975877
42            assigned_room_type_B    -0.041594    0.959259
50            assigned_room_type_K    -0.042837    0.958068
29     distribution_channel_Direct    -0.043222    0.957699
24           market_segment_Direct    -0.045392    0.955623
10               is_repeated_guest    -0.046499    0.954566
57   customer_type_Transient-Party    -0.047693    0.953426
12  previous_bookings_not_canceled    -0.054306    0.947142
43            assigned_room_type_C    -0.067101    0.935101
49            assigned_room_type_I    -0.069153    0.933184
47            assigned_room_type_G    -0.072123    0.930416
46            assigned_room_type_F    -0.086264    0.917352
45            assigned_room_type_E    -0.099278    0.905491
13                 booking_changes    -0.100101    0.904746
26    market_segment_Offline TA/TO    -0.118891    0.887905
44            assigned_room_type_D    -0.165424    0.847534
17       total_of_special_requests    -0.238750    0.787612
16     required_car_parking_spaces    -0.372674    0.688890
0                        Intercept    -2.587113    0.075237
58    reservation_status_Check-Out    -8.656340    0.000174

In [98]:
predicted_proba = reg.predict_proba(x_train)
predicted_proba

array([[9.99914973e-01, 8.50271911e-05],
       [9.99962176e-01, 3.78243952e-05],
       [2.13715288e-04, 9.99786285e-01],
       ...,
       [9.99995039e-01, 4.96086702e-06],
       [9.99962455e-01, 3.75449604e-05],
       [9.99840010e-01, 1.59990342e-04]])

In [99]:
predicted_proba.shape

(95121, 2)

In [100]:
predicted_proba[:,1]

array([8.50271911e-05, 3.78243952e-05, 9.99786285e-01, ...,
       4.96086702e-06, 3.75449604e-05, 1.59990342e-04])